name: fps
description: A Flutter Project Starter CLI
version: 0.0.1

environment:
  sdk: ^3.7.2

dependencies:
  args: ^2.7.0
  io: ^1.0.5    # To help with file creation
  path: ^1.9.1  # Helpful for cross-platform paths

executables:
  fps: bin/fps