name: fpc
description: A simple CLI tool to clean Flutter build folders
version: 0.0.1

environment:
  sdk: ^3.7.2

dependencies:
  args: ^2.7.0
  yaml: ^3.1.3
dev_dependencies:
  lints: ^5.1.1
  test: ^1.25.15
executables:
  fpc:
